### PR TITLE
Update maui-wildfires.html

### PR DESCRIPTION
**Pull request by ivanzvonkov**
Removes mentions of Food Security on the fires resource page.

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
@hannah-rae tagging you because I don't have access to the repo so can't add you as a reviewer officially

**Comment by hannah-rae** [comment]
makes sense to me! thanks!

**Comment by hannah-rae** [comment]
oops sorry didn't mean to close

**Comment by ivanzvonkov** [comment]
I can't merge, so you'll have to if it looks good

**Pull request merged**
